### ISSUE TITLE
issueの提问艺术

### ISSUE THREAD

**Issue by Elegycloud** [Elegycloud/clash-for-linux-backup#12]
注意：当你在使用此项目时，遇到任何无法独自解决的问题请优先前往 Issues 寻找解决方法。由于空闲时间有限，后续将不再对Issues中 “已经解答”、“已有解决方案” 的问题进行重复性的回答。

【标题】问题:xxxxxxxx<br>『问答（需全部复制并回答）』<br>
是否自己检查过日志?:【是/否】</br>
是否自己尝试解决此问题?:【是/否】</br>是否认真详细看过README.md?【是/否】</br>
是否会提供日志并简单概括问题?【是/否】
【联系方式，方便联系（邮件）】
【内容】
xxxxxxxx
【图片】
114514.jpg
![IMG_20231122_125141](https://github.com/Elegybackup/clash-for-linux-backup/assets/150222729/c8946676-d737-45be-be1f-446dec50511c)

**Comment by Elegybackup** [comment]
注意：当你在使用此项目时，遇到任何无法独自解决的问题请优先前往 Issues 寻找解决方法。由于空闲时间有限，后续将不再对Issues中 “已经解答”、“已有解决方案” 的问题进行重复性的回答。
