### ISSUE TITLE
求助大佬centos 安装成功后，在网页可以看到所有节点，但是点击节点后，ping 不通google，没有连接

### ISSUE THREAD

**Issue by lazyjun0927** [Elegycloud/clash-for-linux-backup#23]
centos7没有图形化界面

环境变量和端口都没问题
![image](https://github.com/Elegycloud/clash-for-linux-backup/assets/127071058/773de42b-be87-4597-a92d-8a5045501111)

求大佬帮助，网页端是不是只要双击节点就算连接了？

**Comment by Yizuko** [comment]
多看看README

**Comment by Elegycloud** [comment]
需要在终端输入proxy_on

**Comment by lazyjun0927** [comment]
proxy_on了，readme仔细看过了，确实网页版也没什么其他操作按钮了，不过就很奇怪ping不通google，但可以ping 通openai，调OpenAI的API,就想问问大佬

**Comment by Elegycloud** [comment]
> proxy_on了，readme仔细看过了，确实网页版也没什么其他操作按钮了，不过就很奇怪ping不通google，但可以ping 通openai，调OpenAI的API,就想问问大佬

正常现象，谷歌屏蔽了部分服务器IP，只要检测到你的IP是来自某某机房并且不是用合理的手段去访问（比如Ping）就会出现ping不通的现象，如果你想服务器访问谷歌搜索引擎，可以安装GUI界面，不过嘛，其他谷歌的站点貌似能通，比如谷歌云盘直链
