### ISSUE TITLE
start.sh 报错

### ISSUE THREAD

**Issue by hao-xiaoxing** [Elegycloud/clash-for-linux-backup#26]
输入sudo bash start.sh报错
![iwEcAqNqcGcDAQTRBQAF0QPBBrC_pVaDGIHs6AVwjG1A8VkAB9Ij0cC9CAAJomltCgAL0gADApg jpg_720x720q90](https://github.com/Elegycloud/clash-for-linux-backup/assets/63962391/06d701ca-b04c-421b-bebc-64af0c7b7adc)

CLASH_URL在windows上已验证可用（目前在用），请问需要提前在Ubuntu系统设置系统代理吗，如果需要，需要怎么设置。

**Comment by Elegycloud** [comment]
proxy_off
执行后再次尝试，若还是无法使用，请检查服务器网络

**Comment by hao-xiaoxing** [comment]
> proxy_off 执行后再次尝试，若还是无法使用，请检查服务器网络

执行时会报错：      proxy_off:未找到命令

**Comment by Yizuko** [comment]
检查服务器网络，然后更换机场域名，有可能是地区问题把机场域名墙了

**Comment by hao-xiaoxing** [comment]
服务器网络没有问题，机场域名在哪更改？

**Comment by Yizuko** [comment]
> 服务器网络没有问题，机场域名在哪更改？

机场一般会配置多个域名，更换试试看

**Comment by hao-xiaoxing** [comment]
start,sh启动失败，后续好像都没法操作

**Comment by Yizuko** [comment]
提供图片

**Comment by yeamu** [comment]
![Snipaste_2023-12-25_10-34-51](https://github.com/Elegycloud/clash-for-linux-backup/assets/74447860/f4be5d49-fbbe-4bd2-9aad-4e688f377d2a)

**Comment by Yizuko** [comment]
重新克隆
