### ISSUE TITLE
config文件配置不成功

### ISSUE THREAD

**Issue by DOWOJU** [Elegycloud/clash-for-linux-backup#28]
**情况**
我在虚拟机中按照教程配置.env文件后，运行start.sh脚本能够更新配置文件
在开发板上进行相同的操作后，得到的配置文件一直是如图所示。
这看起来像是一个默认文件，而不是机场的订阅文件
![123](https://github.com/Elegycloud/clash-for-linux-backup/assets/79581458/7eefc821-0b75-409d-af65-897ed7e69bde)
![234](https://github.com/Elegycloud/clash-for-linux-backup/assets/79581458/05ca9115-2ecc-4b9a-9eff-c60f39ca9652)

**Comment by Yizuko** [comment]
下载失败，机场地址问题，检查机场的订阅地址下载下来文件的是否为clash格式

**Comment by DOWOJU** [comment]
同一个订阅地址在两个的机器下一个转换了，一个没有转换
![1](https://github.com/Elegycloud/clash-for-linux-backup/assets/79581458/fb4de663-2483-495e-90fc-53a11ea4fa5a)
![2](https://github.com/Elegycloud/clash-for-linux-backup/assets/79581458/919f8a54-561e-4d32-9b58-6b33fc6cbab3)
