### ISSUE TITLE
终端界面，选择代理节点为空

### ISSUE THREAD

**Issue by hannah-chy** [Elegycloud/clash-for-linux-backup#29]
按照操作成功启动clash服务（P1），但始终无法上网。

尝试用终端选择代理节点，发现节点为空（P2），求助
![29611703429475_ pic](https://github.com/Elegycloud/clash-for-linux-backup/assets/152754240/9c158c31-c950-4cce-a65b-96bdeb75c18c)
![29621703432864_ pic](https://github.com/Elegycloud/clash-for-linux-backup/assets/152754240/c2e837cd-e049-4c60-8c33-e5d760612761)

**Comment by Yizuko** [comment]
机场地址问题，检查机场地址是否正确

**Comment by hannah-chy** [comment]
> 机场地址问题，检查机场地址是否正确

请问是检查机场地址是否正确，是指更换CLASH_URL吗？

**Comment by whr3430633** [comment]
这里难道不是需要安装jq吗

**Comment by Billccx** [comment]
同样的问题，请问是怎么回事？机场地址正确

**Comment by koalaaaaaaaaa** [comment]
> 按照操作成功启动clash服务（P1），但始终无法上网。
> 
> 尝试用终端选择代理节点，发现节点为空（P2），求助 ![29611703429475_ pic](https://private-user-images.githubusercontent.com/152754240/292679625-9c158c31-c950-4cce-a65b-96bdeb75c18c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNzM2MjUsIm5iZiI6MTcwODI3MzMyNSwicGF0aCI6Ii8xNTI3NTQyNDAvMjkyNjc5NjI1LTljMTU4YzMxLWM5NTAtNGNjZS1hNjViLTk2YmRlYjc1YzE4Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxNjIyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODVkMDhhMmEyNzM1MmZjNGQ3ODJjMGZmNWE1NjJiM2FjMDE0OWYxZTBiOTcxMTE2ZDExOGEyNzk4MmRjNjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-XJ9gP6iwQIMsqDMlh-suiN7vY1kFW7TSuToMA3VHSs) ![29621703432864_ pic](https://private-user-images.githubusercontent.com/152754240/292679629-c2e837cd-e049-4c60-8c33-e5d760612761.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNzM2MjUsIm5iZiI6MTcwODI3MzMyNSwicGF0aCI6Ii8xNTI3NTQyNDAvMjkyNjc5NjI5LWMyZTgzN2NkLWUwNDktNGM2MC04YzMzLWU1ZDc2MDYxMjc2MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxNjIyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDQ5NjAyNjkzYTA4OTI1OGE1YjM3MGM2MTNhOTQzNzg3NTBmNjFjZTc0MTZiMjA0Yjg5Yjk4OWUxNWM4YTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Emziwq6xhYyfPNFplM3-gNAwpetbQjexkrrE-zlts9U)

@hannah-chy @Billccx 请问有解决代理节点为空的问题了嘛

**Comment by iockx** [comment]
![image](https://github.com/Elegycloud/clash-for-linux-backup/assets/102414046/77853031-efbb-405b-aac4-f7222f421e0d)
我这里也出现这个问题了，不过我这里就一个节点，在windows上面是默认的

**Comment by Yuzi0123** [comment]
我也是这个问题，请问解决了吗？
