### ISSUE TITLE
无故网络高占用

### ISSUE THREAD

**Issue by cmulittlechild** [Elegycloud/clash-for-linux-backup#30]
在这个项目原作者没有删库的时候我就遇到过这个问题，当时原作者好像说的是流量回环，具体原因未知，基本把带宽占满了，好像也没有修复。
如图，此时并没有在下载东西，重启服务器后，只要运行clash，就会这样。
shutdown停止clash后，网络占用即恢复正常。

<img width="1048" alt="image" src="https://github.com/Elegycloud/clash-for-linux-backup/assets/31565938/71db5d11-a376-48d0-927f-80ed2c30c700">

<img width="739" alt="image" src="https://github.com/Elegycloud/clash-for-linux-backup/assets/31565938/f24b19e8-f697-43e7-9a01-fec7c5922b4f">

**Comment by Yizuko** [comment]
本仓库维护者沉迷与崩坏星穹铁道
（他还没阮梅）
有能力可以尝试自己解决一下，谢谢
如果解决了方便分享一下思路，让我们对这个项目进行修复及优化

**Comment by yhuhuhulwkd** [comment]
metoo

**Comment by yk233** [comment]
我这里也出现了这个问题

**Comment by 857957495** [comment]
加一

**Comment by qwtoe** [comment]
加一，一运行就内存占满，终端卡住
