### ISSUE TITLE
Clash Dashboard 访问地址: http://<ip>:9090/ui  为什么我这里就没有弹出ip的具体地址呢？

### ISSUE THREAD

**Issue by cowhoq** [Elegycloud/clash-for-linux-backup#32]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Yizuko** [comment]
为什么不会弹出呢？

**Comment by Wengzkk** [comment]
> 为什么不会弹出呢？
> 
> 为什么不会弹出呢？您好 ，请问问题怎么解决的？

**Comment by ykw3333** [comment]
一样情况，怎么办哥们？
