### ISSUE TITLE
yacd那个管理界面，添加url地址显示Unauthorized

### ISSUE THREAD

**Issue by aidenchn** [Elegycloud/clash-for-linux-backup#36]
感谢大佬，我能用了，只是在yacd那个界面添加地址的时候显示Unauthorized，登陆http://<ip>:9090也是显示Unauthorized，请问这个问题能解决么，不胜感激

**Comment by ayuxy** [comment]
同样问题😭

**Comment by nanfangAlan** [comment]
同样问题😭

**Comment by Yizuko** [comment]
地址http://IP:9090/ui

**Comment by javaboomBird** [comment]
要使用config文件夹中config.yaml的secret
