### ISSUE TITLE
Unauthorized for login

### ISSUE THREAD

**Issue by khan-yin** [Elegycloud/clash-for-linux-backup#46]
Hello，what's the reason for this, well, I haven't sudo but the start.sh is succeed, is it can used?
![image](https://github.com/Elegycloud/clash-for-linux-backup/assets/50772219/fbd9d17e-0b59-4271-8625-9160ed77e0f3)
![image](https://github.com/Elegycloud/clash-for-linux-backup/assets/50772219/2de18602-5a6e-41b5-81bc-9ae6c83121f9)

![image](https://github.com/Elegycloud/clash-for-linux-backup/assets/50772219/59a1ade7-03c2-4381-afab-0c06ed468bcc)

**Comment by khan-yin** [comment]
have solved, port already used

**Comment by qihanghou726** [comment]
怎么解决的？？我也是这个问题

**Comment by khan-yin** [comment]
重新启动就行，把之前的记录和端口占用都先kill掉

**Comment by jojowhoooo** [comment]
> 重新启动就行，把之前的记录和端口占用都先kill掉

bash restart.sh
