### ISSUE TITLE
socks5://127.0.0.1:7890代理不了，是不支持socks5吗

### ISSUE THREAD

**Issue by jamiescou** [Elegycloud/clash-for-linux-backup#70]
socks5://127.0.0.1:7890代理不了，是不支持socks5吗，http是可以的
<img width="775" alt="image" src="https://github.com/Elegycloud/clash-for-linux-backup/assets/15727736/13443100-baf0-4692-9b0e-b5d12c85319f">

**Comment by jamiescou** [comment]
更换端口就可以了，close

**Comment by HarlayZhang** [comment]
你好 请教一下 请问是在哪更换端口 是config.yaml文件里面吗
