### ISSUE TITLE
疑似有恶意程序

### ISSUE THREAD

**Issue by AimLuo** [Elegycloud/clash-for-linux-backup#76]
从 23 号安装到服务器，在疯狂跑流量。服务器欠费了才发现。
之前明明已经关闭了运行,
就刚刚查看了运行的进程，发现进程还在。
而且服务器在疯狂的跑流量
关闭进程之后流量马上恢复正常

**Comment by AimLuo** [comment]
时间刚好对的上，从23号晚上安装完，流量激增。
![img_v3_02d6_af201f59-fcb2-476f-b731-8cba4902639g](https://github.com/user-attachments/assets/117034ef-21bc-4bc5-b69c-4f3e8129ae2a)

**Comment by KitanoSakurana** [comment]
関連するプロセス名とプロセス資料を提供してください

**Comment by narwhrl** [comment]
一样的情况

**Comment by WYXsb** [comment]
我也遇到了流量偷跑得问题，同样怀疑是这个项目出了漏洞

**Comment by la02w** [comment]
是7890端口被攻击了 进xxx/ui 配置把http代理端口改了

**Comment by jiuanchen** [comment]
> 是7890端口被攻击了 进xxx/ui 配置把http代理端口改了

你好，可以请教一下具体的操作吗。我在config.yaml看到了相关的代理配置，
“”“
# HTTP 代理端口
port: 7890 

# SOCKS5 代理端口
socks-port: 7891 

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892 
”“”
这个端口号是三个都要改一个其他任意连续的四位数就可以吗。

**Comment by jiuanchen** [comment]
> 是7890端口被攻击了 进xxx/ui 配置把http代理端口改了

你好，可以请教一下具体的操作吗。我在config.yaml看到了相关的代理配置，
‘’‘

HTTP 代理端口
port: 7890

SOCKS5 代理端口
socks-port: 7891

Linux 和 macOS 的 redir 代理端口
redir-port: 7892
‘’‘
这个端口号是三个都要改一个其他任意连续的四位数就可以吗。

**Comment by la02w** [comment]
> > 是7890端口被攻击了 进xxx/ui 配置把http代理端口改了
> 
> 你好，可以请教一下具体的操作吗。我在config.yaml看到了相关的代理配置， ‘’‘
> 
> HTTP 代理端口 port: 7890
> 
> SOCKS5 代理端口 socks-port: 7891
> 
> Linux 和 macOS 的 redir 代理端口 redir-port: 7892 ‘’‘ 这个端口号是三个都要改一个其他任意连续的四位数就可以吗。

我是用别人备份的仓库，这个应该也一样，用9090端口的web页面修改http端口，例如
![image](https://github.com/user-attachments/assets/0404d7db-01ac-4b98-b7c8-d1638b956e86)
改了之后就没偷跑过了。只要是start.sh启动之后服务是一直在后台运行的，本地代理使用环境变量127.0.0.1:7890，要是把端口转发出去后，别人或者你自己能直接用公网ip:7890方式跑流量。所以要把默认端口改了，我是只改了http端口，其他两个默认。

**Comment by jiuanchen** [comment]
> start.sh启动之后服务是一直在后台运行的，本地代理使用环境变量
好的，感谢感谢

**Comment by jiuanchen** [comment]
> > > 是7890端口被攻击了 进xxx/ui 配置把http代理端口改了
> > 
> > 
> > 你好，可以请教一下具体的操作吗。我在config.yaml看到了相关的代理配置， ‘’‘
> > HTTP 代理端口 port: 7890
> > SOCKS5 代理端口 socks-port: 7891
> > Linux 和 macOS 的 redir 代理端口 redir-port: 7892 ‘’‘ 这个端口号是三个都要改一个其他任意连续的四位数就可以吗。
> 
> 我是用别人备份的仓库，这个应该也一样，用ip:9090/ui的web页面修改http端口，例如 ![image](https://private-user-images.githubusercontent.com/59063603/370547366-0404d7db-01ac-4b98-b7c8-d1638b956e86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDI4NDgsIm5iZiI6MTcyNzI0MjU0OCwicGF0aCI6Ii81OTA2MzYwMy8zNzA1NDczNjYtMDQwNGQ3ZGItMDFhYy00Yjk4LWI3YzgtZDE2MzhiOTU2ZTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA1MzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMmE0ZjA3YmE0NTJjMDBlYzdkMjJlNmE1NjM1ZTY2YThjYzI0OGVlODEwZTQ3MGUxYjY5YjljNzZmMzU1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c92psMkmy6S5wTBEDelY3pR0tp_x3Vbp1C89AWYrLCc) 改了之后就没偷跑过了。只要是start.sh启动之后服务是一直在后台运行的，本地代理使用环境变量127.0.0.1:7890，要是把端口转发出去后，别人或者你自己能直接用公网ip:7890方式跑流量。所以要把默认端口改了，我是只改了http端口，其他两个默认。

好的，感谢感谢

**Comment by whiteblock1024** [comment]
配置文件 clash-for-linux-backup/conf/config.yaml 中
allow-lan: true 改为 false

**Comment by CaesarWWK** [comment]
被人攻击的 不是这个程序的问题，按照上面大家说的改好就行

**Comment by HarlayZhang** [comment]
> 配置文件 clash-for-linux-backup/conf/config.yaml 中 allow-lan: true # 改为 false external-controller: # 在服务器上为0.0.0.0:xxxx的话建议改为127.0.0.1:xxxx然后走端口转发访问



> > > 是7890端口被攻击了 进xxx/ui 配置把http代理端口改了
> > 
> > 
> > 你好，可以请教一下具体的操作吗。我在config.yaml看到了相关的代理配置， ‘’‘
> > HTTP 代理端口 port: 7890
> > SOCKS5 代理端口 socks-port: 7891
> > Linux 和 macOS 的 redir 代理端口 redir-port: 7892 ‘’‘ 这个端口号是三个都要改一个其他任意连续的四位数就可以吗。
> 
> 我是用别人备份的仓库，这个应该也一样，用ip:9090/ui的web页面修改http端口，例如 ![image](https://github.com/user-attachments/assets/0404d7db-01ac-4b98-b7c8-d1638b956e86) 改了之后就没偷跑过了。只要是start.sh启动之后服务是一直在后台运行的，本地代理使用环境变量127.0.0.1:7890，要是把端口转发出去后，别人或者你自己能直接用公网ip:7890方式跑流量。所以要把默认端口改了，我是只改了http端口，其他两个默认。

你好 可以私聊请教一下是什么问题吗? 为什么我用 proxy_on显示开启了代理后 网页看不见 可以请教一下吗
